sudo: false
language: node_js
os:
  - linux
node_js:
  - stable 

install:
  - npm install
script:
  # - npm run lint
  # - npm run build
  - npm run coveralls
deploy:
  provider: npm
  email: 315779478@qq.com
  api_key: "$NPM_TOKEN" 
  on: 
    branch: master
    tags: true
  tag: latest
  condition: '$TRAVIS_TAG =~ ^v[0-9]+.[0-9]+.[0-9]+$'

after_script:
  - echo after_script