sudo: false
language: node_js
os:
  - linux
node_js:
  - stable 

install:
  - npm install
script:
  # - npm run lint
  # - npm run build
  - npm run coveralls

after_success:
  - npm version patch
  - git commit -am 'chore:build'
  - git set remote add upstream "https://'${GITHUB_TOKEN}'@github.com/roftLin/dp.git"
  - git fetch upstream
  - git remote -v
  # - npm config set '//registry.npmjs.org/:_authToken' "${NPM_TOKEN}" && npm publish --access public
  # - npm config set '//npm.pkg.github.com/:_authToken' "${GITHUB_TOKEN}" && npm publish --access public
  - git push --tags

# deploy:
#   provider: npm
#   email: 315779478@qq.com
#   api_key: "$NPM_TOKEN" 
#   skip_cleanup: true
#   on: 
#     branch: master
#     tags: true
#     tag: latest
#     condition: '$TRAVIS_TAG =~ ^v[0-9]+.[0-9]+.[0-9]+$'
notifications:
  email:
    recipients:
      - 315779478@qq.com
    on_success: never # default: change
    on_failure: always # default: always  