sudo: false
language: node_js
os:
  - linux
node_js:
  - stable 

before_script:
  - echo before_script

jobs:
  include:
    - stage: install
      script: npm install
    - stage: build
      script: echo build
    - stage: test
      script: npm run coveralls -repotoken $COVERALLS_TOKEN
    - stage: deploy
      script: echo deploy
      deploy:
        provider: npm
        api_key: "$NPM_TOKEN" 
        on: 
          branch: master
          tags: true

after_script:
  - echo after_script
  