sudo: false
language: node_js
os:
  - linux
  # - osx
node_js:
  # - 6
  # - 8
  # - 9
  # - 10
  - stable 
branches:
  only:
  - master
install:
- npm install
script:
  # - npm run lint
  # - npm run build
  # - npm run cover
after_success:
- npm run coveralls
# - npm version patch
# - git commit -am 'chore:build'
- npm config set '//registry.npmjs.org/:_authToken' "${NPM_TOKEN}" && npm publish
- npm publish --access public
# - git push xxxxxxx --tags

