sudo: false
language: node_js
os:
  - linux
node_js:
  - stable 
branches:
  only:
  - master
stages:
  - build
  - test
  - deploy 
before_script:
  - echo before_script
job_build:
  stage: build
  script:
  - echo job_build
job_test_1:
  stage: test
  script:
  - echo job_test_1
job_test_2:
  stage: test
  script:
  - echo job_test_2
job_deploy:
  stage: deploy
  script:
  - echo job_deploy  
after_script:
  - echo after_script 