sudo: false
language: node_js
os:
  - linux
node_js:
  - stable 
branches:
  only:
  - master
before_install:
  - echo before_install
before_script:
  - echo before_script

jobs:
  include:
    - stage: build
      script: echo build
    - stage: test
      script: echo test
    - stage: deploy
      script: echo deploy

after_deploy:
  - echo after_deploy
after_script:
  - echo after_script
