sudo: false
language: node_js
os:
  - linux
node_js:
  - stable 
env:
  global:
    - GH_REF: github.com/roftLin/dp.git
install:
  - npm install
script:
  # - npm run lint
  # - npm run build
  - npm run coveralls

after_success:
  # 1、标志位为true进入发布流程 2、重置标记位，防止下次提交进入发布流程
  - export IS_DEPLOYING=$(cat package.json | grep -Eo '\"isDeploying\":.*'| sed "s/\"isDeploying\":.\(.*\)\1//") &&  [ "$IS_DEPLOYING" == "false" ] && exit 0
  - echo $IS_DEPLOYING

  # git账户验证
  - git config -–global user.name "roftLin"   
  - git config –-global user.email "315779478@qq.com"
  - git checkout master
  - git remote set-url origin https://${GITHUB_TOKEN}@${GH_REF}
  - git remote -v

  # 2、重置标记位，防止下次提交进入发布流程
  - npm run deploy

  # 3、发布到npm
  - export IS_NPMSUCCESS=$(npm config set '//registry.npmjs.org/:_authToken' "${NPM_TOKEN}" && npm publish --access public)
  - echo $IS_NPMSUCCESS
  # # - export IS_GITPKGSUCCESS=$(npm config set '//npm.pkg.github.com/:_authToken' "${GITHUB_TOKEN}" && npm publish --access public)
  # # - echo $IS_GITPKGSUCCESS

  # 4、完成发布后自动打tag
  - npm version patch
  - git push origin --tags
  - git push origin master

# deploy:
#   provider: npm
#   email: 315779478@qq.com
#   api_key: "$NPM_TOKEN" 
#   skip_cleanup: true
#   on: 
#     branch: master
#     tags: true
#     tag: latest
#     condition: '$TRAVIS_TAG =~ ^v[0-9]+.[0-9]+.[0-9]+$'
notifications:
  email:
    recipients:
      - 315779478@qq.com
    on_success: never # default: change
    on_failure: always # default: always 
